using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ChatApp.Api.Migrations
{
    public partial class AddChatConversationsAndMessages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE
    ""CHAT_CONVERSATIONS"" (
            ""CHAT_CONVERSATION_ID"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            ""NAME"" NVARCHAR2(200) NOT NULL,
            ""TYPE"" NUMBER(10) NOT NULL,
            ""CREATED_AT"" TIMESTAMP(7) NOT NULL,
            CONSTRAINT ""PK_CHAT_CONVERSATIONS"" PRIMARY KEY (""CHAT_CONVERSATION_ID"")
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
");

            migrationBuilder.Sql(@"
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE
    ""CHAT_MESSAGES"" (
            ""CHAT_MESSAGE_ID"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            ""CONVERSATION_ID"" NUMBER(10) NOT NULL,
            ""SENDER_USER_ID"" NUMBER(10) NOT NULL,
            ""CONTENT"" NCLOB NOT NULL,
            ""CREATED_AT"" TIMESTAMP(7) NOT NULL,
            ""UPDATED_AT"" TIMESTAMP(7) NOT NULL,
            ""IS_EDITED"" NUMBER(1) NOT NULL,
            CONSTRAINT ""PK_CHAT_MESSAGES"" PRIMARY KEY (""CHAT_MESSAGE_ID""),
            CONSTRAINT ""FK_CHAT_MESSAGES_AUTH_USERS_SENDER_USER_ID"" FOREIGN KEY (""SENDER_USER_ID"") REFERENCES ""AUTH_USERS"" (""AUTH_USER_ID""),
            CONSTRAINT ""FK_CHAT_MESSAGES_CHAT_CONVERSATIONS_CONVERSATION_ID"" FOREIGN KEY (""CONVERSATION_ID"") REFERENCES ""CHAT_CONVERSATIONS"" (""CHAT_CONVERSATION_ID"") ON DELETE CASCADE
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
");

            migrationBuilder.Sql(@"
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ""IX_CHAT_MESSAGES_CONVERSATION_ID"" ON ""CHAT_MESSAGES"" (""CONVERSATION_ID"")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
");

            migrationBuilder.Sql(@"
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ""IX_CHAT_MESSAGES_SENDER_USER_ID"" ON ""CHAT_MESSAGES"" (""SENDER_USER_ID"")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CHAT_MESSAGES");

            migrationBuilder.DropTable(
                name: "CHAT_CONVERSATIONS");
        }
    }
}