// <auto-generated />
using System;
using ChatApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ChatApp.Api.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatApp.Api.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("IMAGE_URL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("PRICE");

                    b.Property<int>("SalesCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SALES_COUNT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOCK_QUANTITY");

                    b.HasKey("ProductId");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("ChatApp.Api.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VOUCHER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("DISCOUNT_AMOUNT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("DISCOUNT_PERCENTAGE");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRY_DATE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("UsageCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USAGE_COUNT");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USAGE_LIMIT");

                    b.HasKey("VoucherId");

                    b.ToTable("VOUCHERS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
